service: cloudvision

provider:
  name: aws
  runtime: python3.6

defaults:
 stage: dev
 region: us-east-1

plugins:
  - serverless-python-requirements
package:
  exclude:
    - .git

functions:
  cloudvision:
    name: lambda-cloudvision
    handler: handler.lambda_handler
    events:
      - http:
          path: ocr_image
          method: post
